CREATE TABLE IF NOT EXISTS users (
                                     id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email     VARCHAR(255) NOT NULL UNIQUE,
    login     VARCHAR(64)  NOT NULL,
    name      VARCHAR(255),
    birthday  DATE
    );

CREATE TABLE IF NOT EXISTS films (
                                     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200) NOT NULL DEFAULT '',
    release_date DATE NOT NULL,
    duration     INT  NOT NULL
    );

CREATE TABLE IF NOT EXISTS friendships (
                                           user_id   BIGINT NOT NULL,
                                           friend_id BIGINT NOT NULL,
                                           PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friend_user   FOREIGN KEY (user_id)   REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_friend_friend FOREIGN KEY (friend_id) REFERENCES users(id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS likes (
                                     film_id BIGINT NOT NULL,
                                     user_id BIGINT NOT NULL,
                                     PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_like_film FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

-- Индексы
CREATE INDEX IF NOT EXISTS idx_friendships_friend ON friendships(friend_id);
CREATE INDEX IF NOT EXISTS idx_likes_user        ON likes(user_id);
