-- USERS
create TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(64)  NOT NULL,
    name     VARCHAR(255),
    birthday DATE
);

-- MPA
create TABLE IF NOT EXISTS mpa_ratings
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(16) NOT NULL UNIQUE
);

-- GENRES
create TABLE IF NOT EXISTS genres
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE
);

-- FILMS
create TABLE IF NOT EXISTS films
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(200) NOT NULL DEFAULT '',
    release_date  DATE         NOT NULL,
    duration      INT          NOT NULL,
    mpa_rating_id SMALLINT,
    CONSTRAINT fk_films_mpa FOREIGN KEY (mpa_rating_id)
        REFERENCES mpa_ratings (id) ON delete RESTRICT
);

-- FRIENDSHIPS
create TABLE IF NOT EXISTS friendships
(
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friend_user FOREIGN KEY (user_id) REFERENCES users (id) ON delete CASCADE,
    CONSTRAINT fk_friend_friend FOREIGN KEY (friend_id) REFERENCES users (id) ON delete CASCADE
);

-- LIKES
create TABLE IF NOT EXISTS likes
(
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_like_film FOREIGN KEY (film_id) REFERENCES films (id) ON delete CASCADE,
    CONSTRAINT fk_like_user FOREIGN KEY (user_id) REFERENCES users (id) ON delete CASCADE
);

-- FILM ↔ GENRES
create TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT   NOT NULL,
    genre_id SMALLINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_fg_film FOREIGN KEY (film_id) REFERENCES films (id) ON delete CASCADE,
    CONSTRAINT fk_fg_genre FOREIGN KEY (genre_id) REFERENCES genres (id) ON delete RESTRICT
);
-- REVIEW (USER ↔ FILM)
create TABLE IF NOT EXISTS review
(
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL,
    useful INT DEFAULT 0,
    FOREIGN KEY (film_id) REFERENCES films(id) ON delete CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE,
    UNIQUE(film_id, user_id)
);

--REVIEW LIKES (USER ↔ REVIEW)
create TABLE IF NOT EXISTS review_likes (
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_like BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id),
    FOREIGN KEY (review_id) REFERENCES review(review_id) ON delete CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON delete CASCADE
);

-- INDEXES
create index IF NOT EXISTS idx_friendships_friend ON friendships (friend_id);
create index IF NOT EXISTS idx_likes_user ON likes (user_id);
create index IF NOT EXISTS idx_film_genres_genre ON film_genres (genre_id);
create index IF NOT EXISTS idx_film_genres_film ON film_genres (film_id);
create index IF NOT EXISTS idx_films_mpa ON films (mpa_rating_id);
